### ISSUE TITLE
Need a system daemon restart when scan.conf change

### ISSUE THREAD

**Issue by thebear44** [geerlingguy/ansible-role-clamav#33]
In the task "Change configuration for the ClamAV daemon" is it possible to add **"notify: restart clamav daemon"**
In fact, if the file scan.conf change the configuration is not reload

Thanks a lot

**Comment by panpomaly** [comment]
I had the same problem and created #32

**Comment by geerlingguy** [comment]
Fixed by #32 — thanks!
