### ISSUE TITLE
No package matching clamav found on RHEL 7

### ISSUE THREAD

**Issue by polongibro** [geerlingguy/ansible-role-clamav#8]
I have been able to execute this within a playbook on RHEL 7, however, after approaching the "ensure ClamAV packages are installed" portion of the playbook it gives me errors stating that 'no package matching 'clamav' were found available.

**Comment by michael-barker** [comment]
I had this same issue and solved it by adding the EPEL repository using [geerlingguy.repo-epel](https://galaxy.ansible.com/geerlingguy/repo-epel).

**Comment by geerlingguy** [comment]
Strange... in my test playbook for molecule (called via Travis CI for CentOS 7 and Debian/Ubuntu both), it doesn't require EPEL.. .https://github.com/geerlingguy/ansible-role-clamav/blob/master/.travis.yml
